language: c
compiler: gcc
script: make
os: linux
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90